/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  MetaTxModule,
  MetaTxModuleInterface,
} from "../../CMTAT_STANDALONE_FLAT.sol/MetaTxModule";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class MetaTxModule__factory {
  static readonly abi = _abi;
  static createInterface(): MetaTxModuleInterface {
    return new utils.Interface(_abi) as MetaTxModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MetaTxModule {
    return new Contract(address, _abi, signerOrProvider) as MetaTxModule;
  }
}
